name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you are using

    - name: Install Miniconda on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Install Miniconda on Windows
      if: matrix.os == 'windows-latest'
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Install Miniconda on macOS
      if: matrix.os == 'macos-latest'
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Initialize conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml

    - name: Activate Conda environment and run tests
      shell: bash -l {0}
      run: |
        conda activate det3pa
        python -m unittest discover -s tests
