name: Upload Python Package to PyPI and Deploy Documentation to Read the Docs

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI and Deploy Documentation
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Initialize Conda
        run: |
          conda init bash
        shell: bash

      - name: Create Conda environment
        run: |
          conda env create -f environment.yaml

      - name: Activate Conda environment
        run: |
          source ~/.bashrc
          conda activate MED3pa
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel setuptools-scm sphinx sphinx_rtd_theme

      - name: Clean dist directory
        run: |
          rm -rf dist/

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel  # Could also be python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          skip-existing: true

      - name: Build documentation
        run: |
          conda activate MED3pa
          cd docs
          make html
        shell: bash

      - name: Upload documentation to Read the Docs
        env:
          READTHEDOCS_PROJECT: ${{ secrets.READTHEDOCS_PROJECT }}
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
        run: |
          curl -X POST -d "project=${{ env.READTHEDOCS_PROJECT }}" https://readthedocs.org/build/${{ secrets.READTHEDOCS_PROJECT }} -H "Authorization: token ${{ secrets.READTHEDOCS_TOKEN }}"
